<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SingaravelanNandakumars-MacBook-Pro.local" name="co.bytemark.test.orders.OrdersRegressionCases" tests="9" failures="0" timestamp="30 Jan 2018 15:42:42 GMT" time="65.213" errors="2">
  <testcase name="orderItemWithSavedCard" time="17.258" classname="co.bytemark.test.orders.OrdersRegressionCases"/>
  <testcase name="orderItemWithSavedCard" time="1.623" classname="co.bytemark.test.orders.OrdersRegressionCases"/>
  <testcase name="orderItemWithSavedCard" time="2.218" classname="co.bytemark.test.orders.OrdersRegressionCases"/>
  <testcase name="orderItemWithSavedCard" time="11.437" classname="co.bytemark.test.orders.OrdersRegressionCases"/>
  <testcase name="orderItemWithSavedCard" time="14.206" classname="co.bytemark.test.orders.OrdersRegressionCases"/>
  <testcase name="orderItemWithSavedCard" time="8.120" classname="co.bytemark.test.orders.OrdersRegressionCases"/>
  <testcase name="orderItemWithSavedCard" time="5.540" classname="co.bytemark.test.orders.OrdersRegressionCases"/>
  <testcase name="orderItemWithSavedCard" time="1.566" classname="co.bytemark.test.orders.OrdersRegressionCases">
    <error type="java.lang.AssertionError" message="expected [This credit card is invalid or was not found.  Please supply valid user_uuid along with credit_card_uuid and private_key, or credit_card identifiers and try ag] but found [This credit card is invalid or was not found.  Please supply valid user_uuid along with credit_card_uuid and private_key, or credit_card identifiers and try again.]">
      <![CDATA[java.lang.AssertionError: expected [This credit card is invalid or was not found.  Please supply valid user_uuid along with credit_card_uuid and private_key, or credit_card identifiers and try ag] but found [This credit card is invalid or was not found.  Please supply valid user_uuid along with credit_card_uuid and private_key, or credit_card identifiers and try again.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at co.bytemark.helper.Then.assertEquals(Then.java:48)
	at co.bytemark.test.orders.OrdersRegressionCases.orderItemWithSavedCard(OrdersRegressionCases.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- orderItemWithSavedCard -->
  <testcase name="orderItemWithSavedCard" time="3.245" classname="co.bytemark.test.orders.OrdersRegressionCases">
    <error type="java.lang.AssertionError" message="expected [This credit card is invalid or was not found.  Please supply valid user_uuid along with credit_card_uuid and private_key, or credit_card identifiers and try ag] but found [This credit card is invalid or was not found.  Please supply valid user_uuid along with credit_card_uuid and private_key, or credit_card identifiers and try again.]">
      <![CDATA[java.lang.AssertionError: expected [This credit card is invalid or was not found.  Please supply valid user_uuid along with credit_card_uuid and private_key, or credit_card identifiers and try ag] but found [This credit card is invalid or was not found.  Please supply valid user_uuid along with credit_card_uuid and private_key, or credit_card identifiers and try again.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at co.bytemark.helper.Then.assertEquals(Then.java:48)
	at co.bytemark.test.orders.OrdersRegressionCases.orderItemWithSavedCard(OrdersRegressionCases.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- orderItemWithSavedCard -->
</testsuite> <!-- co.bytemark.test.orders.OrdersRegressionCases -->
